# Generated by Django 2.2.2 on 2019-06-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_content', models.CharField(default=None, max_length=10000)),
                ('posted_at', models.DateTimeField(default=None)),
                ('posted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=10000)),
                ('commented_at', models.DateTimeField(null=True)),
                ('comment_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment')),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbposts.User')),
                ('post_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('HAHA', 'HAHA'), ('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], max_length=5)),
                ('type', models.CharField(choices=[('post', 'post'), ('comment', 'comment')], max_length=7)),
                ('comment_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment')),
                ('post_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbposts.User')),
            ],
            options={
                'unique_together': {('post_field', 'comment_field', 'reactor')},
            },
        ),
    ]
