# Generated by Django 2.2.2 on 2019-06-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('pic_url', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_content', models.CharField(default=None, max_length=10000)),
                ('posted_at', models.DateTimeField(default=None)),
                ('posted_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.User')),
                ('reactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fbposts.Reaction')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField()),
                ('comment_content', models.CharField(default='', max_length=10000)),
                ('commenter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.User')),
                ('id1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post')),
                ('id2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment')),
                ('reactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Reaction')),
            ],
            options={
                'unique_together': {('id1', 'id2')},
            },
        ),
    ]
