# Generated by Django 2.2.2 on 2019-06-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment'),
        ),
    ]
