# Generated by Django 2.2.2 on 2019-06-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbposts', '0003_auto_20190628_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='reacted_to_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reacted_to_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('HAHA', 'HAHA'), ('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reactor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fbposts.User'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('reacted_to_post', 'reacted_to_comment')},
        ),
    ]
