# Generated by Django 2.2.2 on 2019-06-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbposts', '0004_auto_20190628_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reacted_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Comment'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reacted_to_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fbposts.Post'),
        ),
    ]
